# metadata
title: Jakob Voß
description: Minimal Homepage
url: http://jakobvoss.de/

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM

theme: jekyll-theme-minimal

gems:
    - jekyll-sitemap

exclude:
    - Gemfile
    - Gemfile.lock
